services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
  app:
    depends_on:
      - db
    restart: on-failure
    image: task-management
    build: .
    ports:
      - "8081:8080"
      - "5005:5005"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      