version: '3.1'

services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  app:
    depends_on:
      - db
    restart: on-failure
    image: task-management
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?serverTimezone=UTC",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "jwt.secret" : "$JWT_SECRET",
        "jwt.expiration" : "$JWT_EXPIRATION",
        "oauth2.providers" : "$OAUTH2_PROVIDERS",
        "oauth2.dropbox.client-id" : "$DROPBOX_CLIENT_ID",
        "oauth2.dropbox.client-secret" : "$DROPBOX_CLIENT_SECRET",
        "oauth2.dropbox.redirect-uri" : "$DROPBOX_REDIRECT_URI",
        "oauth2.dropbox.authorization-uri" : "$DROPBOX_AUTH_URI",
        "oauth2.dropbox.token-uri" : "$DROPBOX_TOKEN_URI",
        "oauth2.dropbox.scope" : "$DROPBOX_SCOPE",
        "oauth2.dropbox.use-refresh-tokens" : "$DROPBOX_REFRESH_TOKENS",
        "oauth2.google.client-id" : "$GOOGLE_CLIENT_ID",
        "oauth2.google.client-secret" : "$GOOGLE_CLIENT_SECRET",
        "oauth2.google.redirect-uri" : "$GOOGLE_REDIRECT_URI",
        "oauth2.google.authorization-uri" : "$GOOGLE_AUTH_URI",
        "oauth2.google.token-uri" : "$GOOGLE_TOKEN_URI",
        "oauth2.google.scope" : "$GOOGLE_SCOPE",
        "oauth2.google.use-refresh-tokens" : "$GOOGLE_REFRESH_TOKENS"
        "dropbox.root.path" : "$GOOGLE_SHARED_FOLDER_ROOT_PATH"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      