logging.level.com.unbidden.jvtaskmanagementsystem=INFO

oauth2.dropbox.use-refresh-tokens=true
oauth2.google.use-refresh-tokens=true

jwt.expiration=600000
jwt.refresh-expiration-hours=24

refresh-token.cleanup.interval=1
refresh-token.cleanup.initial-delay=0
refresh-token.cleanup.max-age-days=7

frontend.base-url=<frontend-url>
cors.allowed-origin-patterns=<frontend-url>

dropbox.root.path=/TMS
