package com.unbidden.jvtaskmanagementsystem.exception;

public enum ErrorType {
    GENERAL_FIELD_VALIDATION,
    GENERAL_MISFORMED_REQUEST,
    GENERAL_AUTHENTICATION_FAILURE,

    PROJECT_NOT_FOUND,

    TASK_NOT_FOUND,

    LABEL_NOT_FOUND,

    USER_NOT_FOUND,

    ATTACHMENT_NOT_FOUND,
    ATTACHMENT_FILE_TOO_LARGE,
    ATTACHMENT_UPLOAD_FAILURE,

    MESSAGE_NOT_FOUND,
    MESSAGE_COMMENT_NOT_FOUND,
    MESSAGE_REPLY_NOT_FOUND,

    OAUTH2_INTERNAL_FAILURE,
    OAUTH2_EXTERNAL_ID_TAKEN,
    OAUTH2_ALREADY_AUTHORIZED,
    OAUTH2_NO_STATE_FOUND,
    OAUTH2_CALLBACK_FAILURE,

    REGISTRATION_USERNAME_TAKEN,
    REGISTRATION_EMAIL_TAKEN,

    EXTERNAL_INTERRUPTED,

    INTERNAL
}
