package com.unbidden.jvtaskmanagementsystem.exception;

public enum ErrorType {
    GENERAL_FIELD_VALIDATION,
    GENERAL_MISFORMED_REQUEST,
    GENERAL_FORBIDDEN,

    AUTH_GENERAL,
    AUTH_EXPIRED_REFRESH_TOKEN,
    AUTH_REVOKED_REFRESH_TOKEN,
    AUTH_INVALID_REFRESH_TOKEN,
    AUTH_NO_REFRESH_TOKEN,

    PROJECT_NOT_FOUND,
    PROJECT_INCONSISTENT_DATE,
    PROJECT_DROPBOX_CONNECTION_ERROR,
    PROJECT_JOIN_DROPBOX_ERROR,

    TASK_NOT_FOUND,
    TASK_DATE_BEFORE_PROJECT_START,
    TASK_DATE_WRONG_INTERVAL,

    LABEL_NOT_FOUND,

    USER_NOT_FOUND,

    ATTACHMENT_NOT_FOUND,
    ATTACHMENT_FILE_TOO_LARGE,
    ATTACHMENT_UPLOAD_FAILURE,
    ATTACHMENT_DOWNLOAD_FAILURE,
    ATTACHMENT_FILE_DELETE_FAILURE,

    MESSAGE_NOT_FOUND,
    MESSAGE_COMMENT_NOT_FOUND,
    MESSAGE_REPLY_NOT_FOUND,

    OAUTH2_INTERNAL_FAILURE,
    OAUTH2_EXTERNAL_ID_TAKEN,
    OAUTH2_ALREADY_AUTHORIZED,
    OAUTH2_NO_STATE_FOUND,
    OAUTH2_CALLBACK_FAILURE,

    REGISTRATION_USERNAME_TAKEN,
    REGISTRATION_EMAIL_TAKEN,

    EXTERNAL_INTERRUPTED,

    INTERNAL
}
